### ISSUE TITLE
About MPI , iSALE2D

### ISSUE THREAD

**Issue by shichaoli-jlu** [isale-code/isale-wiki#4]
Hi, is there anyone here? Is it possible for iSALE2D to implement parallel computing with multiple CPUs? I see that the initialize_mpi() function is called in iSALE2D.F90, but every time I run iSALE2D, only one CPU is working. Is it necessary for special Settings or command  parameters? I didn't find any helpful information in the manual and wiki, MPI is not support in iSALE2D? thanks.

**Comment by tmdavison** [comment]
Hi. iSALE2D has not currently been parallelised with MPI.

**Comment by shichaoli-jlu** [comment]
:(
